# Use root/root as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
    - ./database:/data/db
    ports:
    - 27017:27017
    restart: always